"""Gamepad companion component const."""

from __future__ import annotations

from typing import Final

DOMAIN: Final = "gamepad_companion"
COMPONENT_CLASS: Final = "GamepadCompanion"

CONF_MUTE_PULSE_EFFECT: Final = "mute_pulse_effect"
CONF_RUMBLE_WEAK_LEVEL_SENSOR: Final = "weak_rumble_level_sensor"
CONF_RUMBLE_STRONG_LEVEL_SENSOR: Final = "strong_rumble_level_sensor"
CONF_RUMBLE_WEAK_SENSOR: Final = "weak_rumble_sensor"
CONF_RUMBLE_STRONG_SENSOR: Final = "strong_rumble_sensor"
CONF_PLAYER_NUMBER_SENSOR: Final = "player_number_sensor"
CONF_LEFT_TRIGGER_EFFECT_SENSOR: Final = "left_trigger_effect_sensor"
CONF_RIGHT_TRIGGER_EFFECT_SENSOR: Final = "right_trigger_effect_sensor"
CONF_LEFT_TRIGGER_EFFECT_ACTIVE_SENSOR: Final = "left_trigger_effect_active_sensor"
CONF_RIGHT_TRIGGER_EFFECT_ACTIVE_SENSOR: Final = "right_trigger_effect_active_sensor"
CONF_LEFT_TRIGGER_ZONE_SENSOR_0: Final = "left_trigger_zone_0_sensor"
CONF_LEFT_TRIGGER_ZONE_SENSOR_1: Final = "left_trigger_zone_1_sensor"
CONF_LEFT_TRIGGER_ZONE_SENSOR_2: Final = "left_trigger_zone_2_sensor"
CONF_LEFT_TRIGGER_ZONE_SENSOR_3: Final = "left_trigger_zone_3_sensor"
CONF_LEFT_TRIGGER_ZONE_SENSOR_4: Final = "left_trigger_zone_4_sensor"
CONF_LEFT_TRIGGER_ZONE_SENSOR_5: Final = "left_trigger_zone_5_sensor"
CONF_LEFT_TRIGGER_ZONE_SENSOR_6: Final = "left_trigger_zone_6_sensor"
CONF_LEFT_TRIGGER_ZONE_SENSOR_7: Final = "left_trigger_zone_7_sensor"
CONF_LEFT_TRIGGER_ZONE_SENSOR_8: Final = "left_trigger_zone_8_sensor"
CONF_LEFT_TRIGGER_ZONE_SENSOR_9: Final = "left_trigger_zone_9_sensor"
CONF_RIGHT_TRIGGER_ZONE_SENSOR_0: Final = "right_trigger_zone_0_sensor"
CONF_RIGHT_TRIGGER_ZONE_SENSOR_1: Final = "right_trigger_zone_1_sensor"
CONF_RIGHT_TRIGGER_ZONE_SENSOR_2: Final = "right_trigger_zone_2_sensor"
CONF_RIGHT_TRIGGER_ZONE_SENSOR_3: Final = "right_trigger_zone_3_sensor"
CONF_RIGHT_TRIGGER_ZONE_SENSOR_4: Final = "right_trigger_zone_4_sensor"
CONF_RIGHT_TRIGGER_ZONE_SENSOR_5: Final = "right_trigger_zone_5_sensor"
CONF_RIGHT_TRIGGER_ZONE_SENSOR_6: Final = "right_trigger_zone_6_sensor"
CONF_RIGHT_TRIGGER_ZONE_SENSOR_7: Final = "right_trigger_zone_7_sensor"
CONF_RIGHT_TRIGGER_ZONE_SENSOR_8: Final = "right_trigger_zone_8_sensor"
CONF_RIGHT_TRIGGER_ZONE_SENSOR_9: Final = "right_trigger_zone_9_sensor"
CONF_HEADPHONE_VOLUME_SENSOR: Final = "headphone_volume_sensor"
CONF_SPEAKER_VOLUME_SENSOR: Final = "speaker_volume_sensor"
CONF_MIC_VOLUME_SENSOR: Final = "mic_volume_sensor"
CONF_LED_BRIGHTNESS_SENSOR: Final = "led_brightness_sensor"
CONF_MUTE_LED_SENSOR: Final = "mute_led_sensor"
CONF_LIGHTBAR_RED_SENSOR: Final = "lightbar_red_sensor"
CONF_LIGHTBAR_GREEN_SENSOR: Final = "lightbar_green_sensor"
CONF_LIGHTBAR_BLUE_SENSOR: Final = "lightbar_blue_sensor"
